export default {
  from: 'Все города',
  to: 'Все города',
  dateStart: '30 апреля',
  dateEnd: '30 мая',
  senders: [
    {
      flightNumber: '61TR2E',
      weight: 5,
      airportFrom: 'NOR',
      airportTo: 'VKO',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '62TR2E',
      weight: 7,
      airportFrom: 'NOR',
      airportTo: 'KJA',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '63TR2E',
      weight: 8,
      airportFrom: 'NOR',
      airportTo: 'DME',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '64TR2E',
      weight: 10,
      airportFrom: 'NOR',
      airportTo: 'SVO',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '65TR2E',
      weight: 12,
      airportFrom: 'NOR',
      airportTo: 'MMK',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '66TR2E',
      weight: 3,
      airportFrom: 'NOR',
      airportTo: 'KGD',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '67TR2E',
      weight: 4,
      airportFrom: 'NOR',
      airportTo: 'KZN',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '68TR2E',
      weight: 6,
      airportFrom: 'NOR',
      airportTo: 'KRR',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '69TR2E',
      weight: 11,
      airportFrom: 'NOR',
      airportTo: 'OVB',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '60TR2E',
      weight: 10,
      airportFrom: 'NOR',
      airportTo: 'OMS',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
    {
      flightNumber: '71TR2E',
      weight: 5,
      airportFrom: 'NOR',
      airportTo: 'NLI',
      flightDate: '12 мая',
      sender: {
        name: 'Aleksei Ponomarev',
        phone: '+79531680100',
        email: 'alexei@gmail.com',
        skype: 'aleksei_1990',
      },
      description: 'Сумка небольшая, аккуратная. Внутри рыба и мясо.',
      sumToPay: 3000,
    },
  ],
}