export default {
  carriage: {
    flex: 1,
    flexDirection: 'column',
  },
  navbar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    height: 90,
    paddingLeft: '5%',
    paddingBottom: '3%',
    zIndex: 1,
    backgroundColor: '#efc218',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  headerText: {
    color: '#000',
    fontSize: 18,
    fontWeight: '500',
  },
  burgerStyles: {
    view: {},
    text: {
      color: 'transparent',
      height: '0%',
    },
  },
  mainInfo: {
    height: '17%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#efc218',
  },
  infoRow: {
    display: 'flex',
    flexDirection: 'row',
    paddingTop: '3%',
  },
  tableContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  tableHeader: {
    fontSize: 20,
    fontWeight: '500',
    marginTop: '3%',
  },
  listItem: {
    display: 'flex',
    flexBasis: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: '5%',
    paddingRight: '5%',
    paddingBottom: '5%',
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  itemSection: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    flexBasis: '20%',
  },
  carriageBtn: {
    container: {
      position: 'absolute',
      bottom: 15,
      right: 55,
      left: 55,
      zIndex: 1000,
    },
    view: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      backgroundColor: '#efc218',
      borderRadius: 50,
      height: 60,
      paddingLeft: 10,
      paddingRight: 10,
    },
    text: {
      color: '#000',
      fontWeight: '500',
      fontSize: 18,
    },
  },
}
