export default {
  senderRequest: {
    flex: 1,
    flexDirection: 'column',
  },
  navbar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    height: '12%',
    paddingLeft: '5%',
    paddingBottom: '3%',
    zIndex: 1,
    backgroundColor: '#efc218',
  },
  mainInfoBar: {
    backgroundColor: '#d8ad14',
    height: '8%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userInfoText: {
    paddingTop: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  infoText: {
    color: '#000',
    fontSize: 18,
    fontWeight: '500',
  },
  burgerStyles: {
    view: {},
    text: {
      color: 'transparent',
      height: '0%',
    },
  },
  container: {
    paddingTop: 20,
    paddingLeft: 20,
    paddingRight: 20,
  },
  contacts: {
    marginTop: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 3,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#979797',
    display: 'flex',
    flexDirection: 'column',
  },
  contact: {
    paddingTop: 5,
    paddingBottom: 5,
    display: 'flex',
    flexDirection: 'row',
  },
  contactType: {
    flexBasis: 100,
    color: '#979797',
  },
  contactValue: {
    fontWeight: '500',
    color: '#979797',
  },
  descr: {
    paddingTop: 10,
    paddingBottom: 10,
    color: '#979797',
  },
  offerBtn: {
    container: {},
    view: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#efc218',
      borderRadius: 50,
      height: 60,
      paddingLeft: 10,
      paddingRight: 10,
    },
    text: {
      color: '#000',
      fontWeight: '500',
      fontSize: 18,
    },
  },
  backBtn: {
    container: {},
    view: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fff',
      borderRadius: 50,
      height: 60,
      paddingLeft: 10,
      paddingRight: 10,
    },
    text: {
      color: '#000',
      fontWeight: '500',
      fontSize: 18,
    },
  },
}
